Tried to implement first Timer interrupt
at the moment compilation fails due to memory settings.

The compilation error:
"Program will not fit into available INTERRUPT_VECTORS."

I tried out several memory settings without success...
Somebody else an idea how to fix this?